# https://docs.docker.com/compose/compose-file/#/versioning
version: '3'

services:
    nginx:
        # https://hub.docker.com/_/nginx
        container_name: ukr_nginx
        build: ./docker/nginx
        volumes:
            - ./:/var/www/vhost:cached
        ports:
            - '80:80'
            - '443:443'
        networks:
            docker_network:
                aliases:
                    - uk-restaurants.test

    php:
        # https://hub.docker.com/_/php
        container_name: ukr_php
        build: ./docker/php
        environment:
            PHP_MEMORY_LIMIT: '4G'
            DB_HOST: 'mysql'
            DB_USER: 'root'
            DB_PASSWORD: 'root'
            DB_NAME: 'uk_restaurant_local'
        volumes:
            - ./:/var/www/vhost/:cached
        ports:
            - '9000:9000'
        networks:
            - docker_network

    scheduler:
        # https://hub.docker.com/_/php
        container_name: ukr_php_schedule
        build: ./docker/scheduler
        depends_on:
          - php
        environment:
            PHP_MEMORY_LIMIT: '128M'
            DB_HOST: 'mysql'
            DB_USER: 'root'
            DB_PASSWORD: 'root'
            DB_NAME: 'uk_restaurant_local'
        volumes:
            - ./:/var/www/vhost/:cached
        networks:
            - docker_network

    mysql:
        # https://hub.docker.com/_/mysql
        container_name: ukr_mysql
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'uk_restaurant_local'
        volumes:
            - ./docker/mysql/data:/var/lib/mysql:cached
            - ./docker/mysql/seeds:/docker-entrypoint-initdb.d
        ports:
            - '3306:3306'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        networks:
            - docker_network

    redis:
        # https://hub.docker.com/_/redis/
        container_name: ukr_redis
        build: ./docker/redis
        volumes:
            - ./docker/redis/data:/data
        ports:
            - '6390:6379'
        networks:
            - docker_network
    queue:
        # https://hub.docker.com/_/php
        container_name: ukr_php_queue
        build: ./docker/queue
        depends_on:
            - php
        environment:
            PHP_MEMORY_LIMIT: '128M'
            DB_HOST: 'mysql'
            DB_USER: 'root'
            DB_PASSWORD: 'root'
            DB_NAME: 'uk_restaurant_local'
        volumes:
            - ./:/var/www/vhost/:cached
        networks:
            - docker_network

networks:
    docker_network:
        driver: bridge
